Repository Liatoshynsky-Foundation/lf-admin, pull requests merged in 2025-07, with the labels that each got.

#64 Add all configs from client
  .branchlintrc.config.js
  .husky/pre-commit
  .husky/pre-push
  app/about/page.test.tsx
  app/about/page.tsx
  app/components/Footer.test.tsx
  app/components/Header.test.tsx
  app/layout.test.tsx
  app/layout.tsx
  app/legacy/page.test.tsx
  app/page.test.tsx
  commitlint.config.js
  eslint.config.mjs
  jest.config.ts
  lint-staged.config.js
  next.config.ts
  package-lock.json
  package.json
  prettier.config.js
Labels: dependencies, linter, config

#70 Collapsible Block
  app/globals.css
  app/layout.test.tsx
  app/layout.tsx
  app/shared/components/design-system/collapsible-block/CollapsibleBlock.styles.ts
  app/shared/components/design-system/collapsible-block/CollapsibleBlock.test.tsx
  app/shared/components/design-system/collapsible-block/CollapsibleBlock.tsx
  app/svgr.d.ts
  jest.config.ts
  next.config.ts
  package-lock.json
  package.json
  public/icons/chevron-down.svg
  tsconfig.json
Labels: frontend, design system, feature

#84 Implement cropper modal
  app/lib/utils/CropperHelper.test.tsx
  app/lib/utils/CropperHelper.ts
  app/shared/components/design-system/cropper-modal/CropperModal.styles.ts
  app/shared/components/design-system/cropper-modal/CropperModal.test.tsx
  app/shared/components/design-system/cropper-modal/CropperModal.tsx
  app/shared/components/design-system/cropper-modal/ImageCropper/ImageCropper.styles.ts
  app/shared/components/design-system/cropper-modal/ImageCropper/ImageCropper.test.tsx
  app/shared/components/design-system/cropper-modal/ImageCropper/ImageCropper.tsx
  package-lock.json
  package.json
Labels: frontend, feature

#110 Implement button component
  app/shared/components/design-system/button/Button.styles.ts
  app/shared/components/design-system/button/Button.test.tsx
  app/shared/components/design-system/button/Button.tsx
Labels: frontend, UI/UX

#114 Implement photo block component
  app/lib/utils/readFileAsDataURL.test.ts
  app/lib/utils/readFileAsDataURL.ts
  app/shared/components/design-system/photo-block/PhotoBlock.styles.ts
  app/shared/components/design-system/photo-block/PhotoBlock.test.tsx
  app/shared/components/design-system/photo-block/PhotoBlock.tsx
  app/shared/hooks/use-image-metadata/useImageMetadata.test.ts
  app/shared/hooks/use-image-metadata/useImageMetadata.ts
  public/icons/image.svg
  public/icons/pencil.svg
  public/images/image.png
Labels: frontend, design system, feature

#116 (SP: 1) Added custom link component
  app/shared/components/design-system/link/CustomLink.styles.ts
  app/shared/components/design-system/link/CustomLink.test.tsx
  app/shared/components/design-system/link/CustomLink.tsx
  app/shared/components/design-system/link/NextLink.test.tsx
  app/shared/components/design-system/link/NextLink.tsx
  app/shared/components/svg-image/SvgImage.tsx
Labels: frontend, design system, UI/UX, feature

#112 (SP: ) Move MongoDB Connection and Logger to admin from client
  .env.example
  .gitignore
  app/api/health/route.ts
  app/config/index.test.ts
  app/config/index.ts
  app/constants/errors.ts
  app/constants/index.ts
  app/db/connect.test.ts
  app/db/connect.ts
  app/lib/utils/apiResponse.test.ts
  app/lib/utils/apiResponse.ts
  app/middleware/logger/logger.test.ts
  app/middleware/logger/logger.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies, feature, backend

#117 Added discard changes modal
  app/shared/components/design-system/button/Button.tsx
  app/shared/components/design-system/discard-changes-modal/DiscardChangesModal.styles.ts
  app/shared/components/design-system/discard-changes-modal/DiscardChangesModal.test.tsx
  app/shared/components/design-system/discard-changes-modal/DiscardChangesModal.tsx
  public/icons/warning.svg
Labels: frontend, UI/UX, feature

#119 Add Content to Liatoshynsky foundation Accordion Section
  app/shared/components/about-us/Liatoshynsky-foundation/LiatoshynskyFoundation.const.ts
  app/shared/components/about-us/Liatoshynsky-foundation/LiatoshynskyFoundation.test.tsx
  app/shared/components/about-us/Liatoshynsky-foundation/LiatoshynskyFoundation.tsx
  app/shared/components/about-us/Liatoshynsky-foundation/foundation-block/FoundationBlock.test.tsx
  app/shared/components/about-us/Liatoshynsky-foundation/foundation-block/FoundationBlock.tsx
  app/shared/components/about-us/Liatoshynsky-office/Liatoshynsky-office.const.ts
  app/shared/components/about-us/Liatoshynsky-office/Liatoshynsky-office.test.tsx
  app/shared/components/about-us/Liatoshynsky-office/Liatoshynsky-office.tsx
  app/shared/components/about-us/Liatoshynsky-office/quote-block/QuoteBlock.test.tsx
  app/shared/components/about-us/Liatoshynsky-office/quote-block/QuoteBlock.tsx
  app/types/accordionBlocks.ts
Labels: frontend, feature, tests

#121 feat: add a universal component for displaying and managing lists
  app/shared/components/configurable-list/ConfigurableList.styles.ts
  app/shared/components/configurable-list/ConfigurableList.test.tsx
  app/shared/components/configurable-list/ConfigurableList.tsx
  app/shared/components/configurable-list/item-wrapper/ItemWrapper.styles.ts
  app/shared/components/configurable-list/item-wrapper/ItemWrapper.test.tsx
  app/shared/components/configurable-list/item-wrapper/ItemWrapper.tsx
  app/types/accordionBlocks.ts
  public/icons/plus.svg
  public/icons/trash.svg
Labels: frontend, UI/UX

#123 (SP: 2) Implemented OurGoals accordion
  app/shared/components/accordion-blocks/our-goals/OurGoals.const.ts
  app/shared/components/accordion-blocks/our-goals/OurGoals.styles.ts
  app/shared/components/accordion-blocks/our-goals/OurGoals.test.tsx
  app/shared/components/accordion-blocks/our-goals/OurGoals.tsx
Labels: frontend, UI/UX, feature

#98 Implement snack bar component
  app/shared/components/design-system/alert/Alert.styles.ts
  app/shared/components/design-system/alert/Alert.test.tsx
  app/shared/components/design-system/alert/Alert.tsx
  package-lock.json
  package.json
Labels: frontend, UI/UX, feature

#86 Login Component for Admin Login page
  app/layout.test.tsx
  app/shared/components/Footer/Footer.test.tsx
  app/shared/components/Footer/Footer.tsx
  app/shared/components/LoginModal/LoginModal.styles.ts
  app/shared/components/LoginModal/LoginModal.test.tsx
  app/shared/components/LoginModal/LoginModal.tsx
  app/shared/components/design-system/password-field/PasswordField.styles.ts
  app/shared/components/design-system/password-field/PasswordField.test.tsx
  app/shared/components/design-system/password-field/PasswordField.tsx
  app/shared/components/design-system/text-field/TextField.styles.ts
  package-lock.json
  public/icons/eye-closed.svg
  public/icons/eye.svg
  tsconfig.json
Labels: frontend, UI/UX, feature

#72 Language Switch
  app/shared/components/design-system/button-group/ButtonGroup.styles.ts
  app/shared/components/design-system/button-group/ButtonGroup.test.tsx
  app/shared/components/design-system/button-group/ButtonGroup.tsx
  app/shared/components/language-switcher/LanguageSwitcher.test.tsx
  app/shared/components/language-switcher/LanguageSwitcher.tsx
Labels: frontend, feature

#132 Implement Our Mission block
  app/shared/components/about-us/our-mission/OurMission.contants.ts
  app/shared/components/about-us/our-mission/OurMission.styles.ts
  app/shared/components/about-us/our-mission/OurMission.test.tsx
  app/shared/components/about-us/our-mission/OurMission.tsx
  app/shared/components/configurable-list/item-wrapper/ItemWrapper.styles.ts
  app/shared/components/design-system/button/Button.styles.ts
  app/shared/components/design-system/photo-block/PhotoBlock.tsx
  jest.config.ts
  public/images/image2.png
Labels: frontend, UI/UX

#146 (SP: 0,5) Rename jwt tokens in env file
  .env.example
  src/application/use-cases/tokenService/createToken/createToken.service.ts
  src/application/use-cases/tokenService/createToken/createToken.test.ts
  src/config/index.ts
  src/shared/types/env.d.ts
Labels: refactoring
