Repository Liatoshynsky-Foundation/lf-admin, pull requests merged in 2025-08, with the labels that each got.

#151 (SP: ) Refactor react-query to apollo-client
  app/lib/utils/apollo-client.test.ts
  app/lib/utils/apollo-client.ts
  app/lib/utils/refreshToken.test.ts
  app/lib/utils/refreshToken.ts
  app/login/page.test.tsx
  app/login/page.tsx
  app/shared/components/login-modal/LoginModal.tsx
  app/shared/components/react-query-provider/reactQueryProvider.test.tsx
  app/shared/components/react-query-provider/reactQueryProvider.tsx
  app/shared/hooks/use-graphql/use-graphql-mutation/useGraphqlMutation.test.tsx
  app/shared/hooks/use-graphql/use-graphql-mutation/useGraphqlMutation.ts
  app/shared/hooks/use-graphql/use-graphql-query/useGraphqlQuery.test.tsx
  app/shared/hooks/use-graphql/use-graphql-query/useGraphqlQuery.ts
  app/shared/providers/apollo-client-provider/apolloClientProvider.test.tsx
  app/shared/providers/apollo-client-provider/apolloClientProvider.tsx
  app/shared/providers/body-provider/BodyProvider.test.tsx
  app/shared/providers/body-provider/BodyProvider.tsx
  app/types/graphql/adminLogin.ts
  app/types/graphql/generated/graphql.ts
  app/types/graphql/mutations/adminLogin.graphql
  app/types/graphql/mutations/refreshToken.ts
  app/types/graphql/queries/getAdmin.graphql
  app/types/graphql/refreshTokenGraphQl.ts
  app/types/graphql/testGraphql.ts
  codegen.ts
  package-lock.json
  package.json
  src/interfaces/graphql/resolvers/admin/Query.ts
  src/interfaces/graphql/resolvers/index.ts
  src/interfaces/graphql/schemas/admin.graphql
Labels: dependencies, frontend, refactoring

#167 (SP: 1) Update project documentation #139
  README.md
  public/images/liatoshynsky-thumbnail.jpg
Labels: documentation

#177 Feature/136/page editing header
  app/shared/components/header/Header.styles.ts
  app/shared/components/header/Header.test.tsx
  app/shared/components/header/Header.tsx
  app/shared/components/language-switcher/LanguageSwitcher.tsx
  public/icons/externalLink.svg
Labels: frontend, feature

#161 chore(ci): added image build
  .github/workflows/docker-image.yml
Labels: DevOps

#168 Review and refine CropperModal logic
  app/constants/errors.ts
  app/lib/utils/CropperHelper.ts
  app/shared/components/design-system/cropper-modal/CropperModal.tsx
  app/shared/components/design-system/cropper-modal/ImageCropper/ImageCropper.tsx
  app/types/cropper.ts
Labels: enhancement, frontend

#147 Add content to "Вступна секція" Accordion in Admin Panel
  app/shared/components/about-us/Entry-section/EntrySection.consts.ts
  app/shared/components/about-us/Entry-section/EntrySection.test.tsx
  app/shared/components/about-us/Entry-section/EntrySection.tsx
  app/shared/components/side-navigation/SideNavigation.consts.ts
Labels: frontend, UI/UX

#215 changelog generation
  .github/workflows/release-please.yml
  .release-please-config.json
  package-lock.json
  package.json
  version.txt
Labels: DevOps
